language: bash

sudo: true

install:
  - git clone https://github.com/bats-core/bats-core.git
  - cd bats-core
  - sudo ./install.sh /usr/local

script:
    - cd /home/travis/build/tmc-bash/tmc-bash-runner/
    - bats test/runnerTest.bats